### ISSUE TITLE
Filter out vehicles which crash when using "Merge DLCs" option

### ISSUE THREAD

**Issue by anzz1** [E66666666/GTAVAddonLoader#10]
These "Expanded And Enhanced" vehicles crash the game when spawned (on version 1.0.2699.0 v1.61) and should be filtered out from the menus when "Merge DLCs" option is on. 
```
static const std::vector<Hash> ExpandedAndEnhancedVehicles = {
    0x170341C2, //  Super               CYCLONE2            cyclone2            Cyclone II          
    0x5C54030C, //  Muscle              ARBITERGT           arbitergt           Arbiter GT          
    0x438F6593, //  Sports              S95                 s95                 S95                 
    0x39085F47, //  Super               IGNUS2              ignus2              Weaponized Ignus    
    0xA71D0D4F, //  SUVs                ASTRON2             astron2             Astron Custom       
};
```

**Comment by E66666666** [comment]
het houdt niet op

niet vanzelf

**Comment by E66666666** [comment]
Yes, they're still spawnable and <b><u>WILL crash your game</u></b> when spawned anyway. No, I'm not filtering them out for the off-chance someone puts working files for these models, or for the off-chance of R* adding them in a future update. There's a fat warning now, spawning them is now completely at your own risk.

**Comment by anzz1** [comment]
Warning is a good solution. The problem really was that when using "merge DLCs", the crashy ones were mixed amongst the working ones without anything to tell them apart. Putting a image with the word "CRASH" or something in the img folder for those vehiceles was an option though.

**Comment by E66666666** [comment]
Yeah that was understandable, but I needed to propagate some details (DLC source, notes like the warning) throughout the lists anyway.
