### ISSUE TITLE
"Couldn't load model"

### ISSUE THREAD

**Issue by locomoco28** [E66666666/GTAVAddonLoader#5]
I'm getting the error "couldn't load model" when spawning a modded vehicle

**Comment by E66666666** [comment]
The vehicle probably wasn't installed right or was corrupted in some other way. Other trainers will also give the same message.

**Comment by locomoco28** [comment]
It worked when I deleted and reloaded the preview pictures and then loaded a normal vehicle (had to do it for each add-on vehicle)
