### ISSUE TITLE
error MSB3073: 命令“copy /b F:\C++\GTAVAddonLoader-master\GTAVAddonLoader\main.cpp +,,

### ISSUE THREAD

**Issue by 52mods** [E66666666/GTAVAddonLoader#7]
error MSB3073: 命令“copy /b F:\C++\GTAVAddonLoader-master\GTAVAddonLoader\main.cpp +,,
error MSB3073: :VCEnd”已退出，代码为 1。
请问大佬这这是什么问题呀？

**Comment by E66666666** [comment]
The [prebuild touches the main.cpp file](https://github.com/E66666666/GTAVAddonLoader/blob/master/GTAVAddonLoader/GTAVAddonLoader.vcxproj#L107) to force the build date to update. You can just remove the prebuild line, or figure out what triggers the failure (write access or something).

Also please write your questions in English, I cannot read Chinese.

**Comment by 52mods** [comment]
thank you very much! 谢谢您



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月30日(星期三) 下午2:52
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [E66666666/GTAVAddonLoader] error MSB3073: 命令“copy /b F:\C++\GTAVAddonLoader-master\GTAVAddonLoader\main.cpp +,, (#7)





 
The prebuild touches the main.cpp file to force the build date to update. You can just remove the prebuild line, or figure out what triggers the failure (write access or something).
 
Also please write your questions in English, I cannot read Chinese.
 
&mdash;
